language: node_js
node_js:
- "7"
os: linux
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
- npm i -g gl-transition-scripts
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
- "./scripts/build.sh"
before_deploy:
- cd release
deploy:
  provider: npm
  email: n.lazzaroni@multi-consult.it
  skip_cleanup: true
  api_key:
    secure: 9acf0c46-bbe6-4648-b7c2-8c65e9568a01
  on:
    repo: MultiDigital/gl-transitions
    branch: master
after_deploy:
- sleep 10; ../scripts/tag-and-push.sh
